function net = trainLSTM(x_train,y_train,x_test,y_test,layers,maxEpochs)
    options = trainingOptions('adam', ...
        'ExecutionEnvironment','auto', ...
        'GradientThreshold',1, ...
        'MaxEpochs',maxEpochs, ...
        'MiniBatchSize',32, ...
        'SequenceLength','longest', ...
        'Verbose',0, ...
        'ValidationData',{x_test,y_test}, ...
        'ValidationFrequency',5, ...
        'LearnRateSchedule', 'piecewise', ...
    	'LearnRateDropFactor', 0.8, ...
        'LearnRateDropPeriod', 25, ...
        'Plots','training-progress');

    net = trainNetwork(x_train,y_train,layers,options);
end