%clear;
%load('04_28_csi_dataset.mat');
[x_train, y_train,  x_test, y_test] = split_train_test(csi_train, csi_label, 6, 0.7);%划分训练集和测试集

%对训练集进行排序
[x_train,y_train] = sequenceSort(x_train,y_train);

%使用LSTMMaker函数建立训练网络
train_data_size = size(x_train{1,1});
inputSize = train_data_size(1);
numHiddenUnits = 128;
numClasses = 6;
networkType = 'DoubleBiLSTM';
layers = LSTMMaker(networkType, inputSize, numHiddenUnits, numClasses);

maxEpochs = 50;
miniBatchSize = 32;

options = trainingOptions('adam', ...
    'ExecutionEnvironment','auto', ...
    'GradientThreshold',1, ...
    'MaxEpochs',maxEpochs, ...
    'MiniBatchSize',miniBatchSize, ...
    'SequenceLength','longest', ...
    'Verbose',0, ...
    'ValidationData',{x_test,y_test}, ...
    'ValidationFrequency',5, ...
    'LearnRateSchedule', 'piecewise', ...
    'LearnRateDropFactor', 0.8, ...
    'LearnRateDropPeriod', 20, ...
    'L2Regularization',0.0004,...
    'Plots','training-progress');

net = trainNetwork(x_train,y_train,layers,options);

y_Pred = classify(net,x_test, ...
    'SequenceLength','longest');

[acc,precision,recall,f1]=indicator_calculation(y_test,y_Pred)
 
figure('Units','normalized','Position',[0.2 0.2 0.4 0.4]);
cm = confusionchart(y_test,y_Pred);
cm.Title = 'Confusion Matrix for Validation Data';
cm.ColumnSummary = 'column-normalized';
cm.RowSummary = 'row-normalized';